# Generated by Django 3.0.6 on 2020-05-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200516_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/none/default.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
